MsgBox "Archivo creado y subido Por ing Edison V"
MsgBox "2015"
MsgBox "Visita - http://www.editronikx.com/"
MsgBox "si te sirvio mi trabajo y deseas apoyarme brindame una donacion en paypal"
MsgBox "editronikx@gmail.com"
MsgBox "regalame un clic en  la publicidad y en me gusta"
MsgBox "de esta manera tambien apoyas mi trabajo"
MsgBox "Gracias por descargar"
MsgBox "Pasto Colombia"
MsgBox "http://www.editronikx.com"